version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.0
    steps:
        - checkout  # checkout source code to working directory
        - run:
            command: |  # use pipenv to install dependencies
              sudo pip install pipenv
              pipenv install

              sudo pip install codecov
              codecov

              sudo pip install coverage
              coverage run tests.py
