name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out Git repository
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        id: install
        run: pip install black flake8

      - name: Run flake8
        id: flake8
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          flake8_args: --ignore=E203 --per-file-ignores="src/core/rules.py:F401"

      - name: Run black
        id: black
        uses: wearerequired/lint-action@v1
        with:
          black: true

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Check lint result
        id: check_result
        if: steps.flake8.outcome != 'success' || steps.black.outcome != 'success'
        run: exit 1
