name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run black
        uses: wearerequired/lint-action@v1
        with:
          black: true

      - name: Run flake8
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          flake8_args: --ignore=E203 --per-file-ignores="src/core/rules.py:F401"
