name: Version

on: push

jobs:
  change-version:
    name: Change Version
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out Git repository
        id: checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: get-version
        run: |
          with open("setup.py") as file:
            lines = file.readlines()

          for line in lines:
            if "VERSION = " in line:
                version = line.split(" = ")[1]
          print(version)

        shell: python

      - name: Change version
        id: change-version
        run: echo "$version"
