name: Version

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: 
      - completed

jobs:
  change-version:
    name: Change Version
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out Git repository
        id: checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: get-version
        run: |
          version=$(grep "VERSION = " setup.py)
          IFS=' = ' read -r -a version <<< "$version"
          version="${version[1]}"
          version=$(echo "$version" | sed "s/\"/\ /g")

      - name: Change version
        id: change-version
        run: echo "$version"
